version: '2'
services:
  selenium_hub:
    image: selenium/hub
    ports:
      - 4444
    env_file:
      - ../.env

  chrome:
    depends_on:
      - selenium_hub
    image: selenium/node-chrome-debug:2.53.0
    links:
      - selenium_hub:hub
    ports:
      - 4444
      - 6000:5900
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
    env_file:
      - ../.env

  wdio:
    depends_on:
      - selenium_hub
    links:
      - selenium_hub:selenium
    image: twhtanghk/wdio.inhse
    volumes:
      - ${COMPOSEROOT}/wdio.inhse/data:/webdriverio/errorShots
    env_file:
      - ../.env
      - ./.env
    environment:
      - SERVICE_NAME=wdio
